/**
 * Screenshot manifest for the executive narrative in public/deck.html.
 *
 * Every capture uses the same logical viewport as its live frame. Keeping the
 * route and focus anchor in one place makes the still fallback reproduce the
 * exact product state shown when the deck is connected to the running app.
 */

export default {
  base: 'http://localhost:3000',
  root: '#product',
  out: 'public/shots',
  deck: 'public/deck.html',
  deckUrl: 'http://localhost:3000/deck.html',
  pdf: '../docs/deck/demo.pdf',
  gateCookie: 'demo_gate',

  shots: [
    {
      name: 'july-position',
      url: '/app?view=inner&focus=section-headline',
      w: 1100,
      h: 540,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-headline',
      scrollPad: 14,
      settle: 700,
    },
    {
      name: 'revenue-bridge',
      url: '/app/performance?view=inner&focus=section-bridge',
      w: 1100,
      h: 540,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-bridge',
      scrollPad: 14,
      settle: 700,
    },
    {
      name: 'source-drill',
      url: '/app/explore?view=inner&focus=section-drill&rows=measure&cols=period&drill=0%3A5',
      w: 1100,
      h: 540,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-drill',
      scrollPad: 14,
      settle: 700,
    },
    {
      name: 'version-diff',
      url: '/app/forecast?view=inner&focus=section-diff&version=v7&from=v6',
      w: 1100,
      h: 540,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-diff',
      scrollPad: 14,
      settle: 700,
    },
    {
      name: 'scenario-impact',
      url: '/app/scenarios?view=inner&focus=section-effect&dsoDays=10',
      w: 820,
      h: 460,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-effect',
      scrollPad: 14,
      settle: 700,
    },
    {
      name: 'cash-horizon',
      url: '/app/cash?view=inner&focus=section-weekly',
      w: 820,
      h: 460,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-weekly',
      scrollPad: 14,
      settle: 700,
    },
    {
      name: 'forecast-quality',
      url: '/app/quality?view=inner&focus=section-bias&measure=subcontract_cost',
      w: 1100,
      h: 540,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-bias',
      scrollPad: 14,
      settle: 700,
    },
    {
      name: 'published-commentary',
      url: '/app/commentary?view=inner&focus=section-commentary&state=published',
      w: 1100,
      h: 540,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-commentary',
      scrollPad: 14,
      settle: 700,
    },
    {
      name: 'controls-checks',
      url: '/app/controls?view=inner&focus=section-checks',
      w: 1100,
      h: 540,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-checks',
      scrollPad: 14,
      settle: 700,
    },
    {
      name: 'permission-refusal',
      url: '/app/controls?view=inner&focus=section-permissions&as=gulf-controller&entity=group',
      w: 1100,
      h: 540,
      sel: '#product',
      viewportOnly: true,
      scrollTo: '#section-permissions',
      scrollPad: 14,
      settle: 700,
    },
  ],
};
